platform :ios, '13.1'

target 'Demo-Cocoapods' do
  use_frameworks!

  pod 'EnodeLinkKit', :git => 'https://github.com/enode/enode-link-ios.git', :tag => '1.0.10'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
